
name: Shell Commands

on:
  push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $$GITHUB_WORKSPACE
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python