name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: variable disponible para todos los pasos del job
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $$GITHUB_WORKSPACE
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
      - name: Log ENV variables
        env:
          STEP_ENV: variable disponible para solo este paso
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}" 